AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: SkillCappedFetcher
      CodeUri: src/
      Handler: fetch.handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 60
      Policies:
        - Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Action:
                - "s3:PutObject"
              Resource: "arn:aws:s3:::com.shepherdjerred.better-skill-capped/*"
      Events:
        ScheduleEventSource:
          Type: Schedule
          Properties:
            Schedule: "cron(0 * * * ? *)"
